FROM debian:stable-slim

ARG CMAKE_VER=3.27.8

ENV ARM_GCC_PATH=/opt/gcc-arm-none-eabi

LABEL Description="Image for building and debugging arm-embedded projects using the GCC ARM toolchain (gcc-arm-none-eabi-12.2-rel1). Includes CMake ${CMAKE_VER} and Python 3.11 (debian bookworm default) with pylint and pyserial"
LABEL maintainer="Rob McKay"

# wget is needed to get the toolchain

RUN apt-get update && \
    apt-get install -qq -y ninja-build wget bzip2 xz-utils binutils binutils-common make libpath-tiny-perl python3 python3-pip pylint \
        gcc- cpp- manpages- linux-libc-dev- manpages-dev- --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN python3 -m pip install --upgrade pip
RUN pip3 install --break-system-packages pyserial
RUN cpan -i Digest::CRC

WORKDIR /opt
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VER}/cmake-${CMAKE_VER}-linux-x86_64.sh -O cmake-linux-x86_64.sh -q --no-check-certificate && \
    chmod +x cmake-linux-x86_64.sh && \
    ./cmake-linux-x86_64.sh  --prefix=/opt --include-subdir --skip-licence && \
    rm cmake-linux-x86_64.sh

# get the toolchain
RUN wget https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz -O gcc-arm-none-eabi.tar.xz -q --no-check-certificate && \
    mkdir $ARM_GCC_PATH && \
    tar xf gcc-arm-none-eabi.tar.xz -C $ARM_GCC_PATH --strip-components 1 && \
    rm gcc-arm-none-eabi.tar.xz && \
    rm -rf $ARM_GCC_PATH/share/doc/ $ARM_GCC_PATH/share/gcc-arm-none-eabi/samples/
    
# add the tools to the path
ENV PATH="/opt/cmake-${CMAKE_VER}-linux-x86_64/bin:$ARM_GCC_PATH/bin:${PATH}"
WORKDIR /home/build
